# Generated by Django 5.1.6 on 2025-03-02 15:24

import os
from pathlib import Path

from django.db import migrations


def run_sql(apps, schema_editor):
    text = Path(os.path.dirname(__file__), "play-1-101.sql").read_text()

    with schema_editor.connection.cursor() as cursor:
        for chunk in text.split(";"):
            if chunk.strip():
                print(chunk)
                cursor.execute(chunk)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunPython(run_sql, migrations.RunPython.noop),
    ]
