# Generated by Django 5.1.6 on 2025-10-01 21:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dst", "0001_play"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("password", models.TextField(db_column="hashed_password")),
                ("is_active", models.BooleanField(db_column="active", default=True)),
                ("name", models.TextField()),
                ("email", models.TextField()),
                ("email_validated", models.BooleanField(default=False)),
            ],
            options={
                "db_table": 'public"."users',
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("num", models.TextField()),
                ("deleted", models.BooleanField(default=False)),
                ("content", models.TextField()),
            ],
            options={
                "db_table": "entry",
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
            ],
            options={
                "db_table": "meeting",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("short_name", models.TextField()),
                ("timezone", models.TextField()),
                ("late_time", models.TimeField()),
                ("printer_email", models.TextField(blank=True, null=True)),
                ("jc_reset_day", models.IntegerField(blank=True, null=True)),
                ("show_last_modified_in_print", models.BooleanField(default=False)),
                ("show_history_in_print", models.BooleanField(default=False)),
                ("show_custodia", models.BooleanField(default=False)),
                ("show_attendance", models.BooleanField(default=False)),
                ("show_electronic_signin", models.BooleanField(default=False)),
                ("show_accounting", models.BooleanField(default=False)),
                ("show_roles", models.BooleanField(default=False)),
                ("enable_case_references", models.BooleanField(default=False)),
                ("attendance_enable_off_campus", models.BooleanField(default=False)),
                ("attendance_show_reports", models.BooleanField(default=False)),
                (
                    "attendance_report_latest_departure_time",
                    models.TimeField(blank=True, null=True),
                ),
                (
                    "attendance_report_latest_departure_time_2",
                    models.TimeField(blank=True, null=True),
                ),
                (
                    "attendance_report_late_fee",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "attendance_report_late_fee_2",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "attendance_report_late_fee_interval",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "attendance_report_late_fee_interval_2",
                    models.IntegerField(blank=True, null=True),
                ),
                ("attendance_show_percent", models.BooleanField(default=False)),
                (
                    "attendance_show_weighted_percent",
                    models.BooleanField(default=False),
                ),
                ("attendance_show_rate_in_checkin", models.BooleanField(default=False)),
                ("attendance_enable_partial_days", models.BooleanField(default=False)),
                (
                    "attendance_day_latest_start_time",
                    models.TimeField(blank=True, null=True),
                ),
                (
                    "attendance_day_earliest_departure_time",
                    models.TimeField(blank=True, null=True),
                ),
                ("attendance_day_min_hours", models.FloatField(blank=True, null=True)),
                (
                    "attendance_partial_day_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "attendance_admin_pin",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "attendance_default_absence_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "attendance_default_absence_code_time",
                    models.TimeField(blank=True, null=True),
                ),
                ("roles_individual_term", models.TextField(blank=True, null=True)),
                ("roles_committee_term", models.TextField(blank=True, null=True)),
                ("roles_group_term", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "organization",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "task",
            },
        ),
        migrations.CreateModel(
            name="LinkedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_user_id", models.TextField()),
                ("provider_key", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": 'public"."linked_account',
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.meeting"
                    ),
                ),
            ],
            options={
                "db_table": "case",
            },
        ),
        migrations.AddField(
            model_name="meeting",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="dst.organization"
            ),
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("num", models.TextField()),
                ("deleted", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.organization",
                    ),
                ),
            ],
            options={
                "db_table": "chapter",
            },
        ),
        migrations.CreateModel(
            name="AttendanceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.organization",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_rule",
            },
        ),
        migrations.CreateModel(
            name="AttendanceCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.organization",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_code",
            },
        ),
        migrations.CreateModel(
            name="AllowedIp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.TextField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.organization",
                    ),
                ),
            ],
            options={
                "db_table": "allowed_ips",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.organization",
                    ),
                ),
            ],
            options={
                "db_table": "account",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="dst.organization"
            ),
        ),
        migrations.CreateModel(
            name="OrganizationHost",
            fields=[
                ("host", models.TextField(primary_key=True, serialize=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hosts",
                        to="dst.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_hosts",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("first_name", models.CharField()),
                ("last_name", models.CharField()),
                ("display_name", models.CharField()),
                ("email", models.CharField(blank=True)),
                ("gender", models.CharField(blank=True)),
                ("address", models.CharField(blank=True)),
                ("city", models.CharField(blank=True)),
                ("state", models.CharField(blank=True)),
                ("zip", models.CharField(blank=True)),
                ("neighborhood", models.CharField(blank=True)),
                (
                    "id",
                    models.IntegerField(
                        db_column="person_id", primary_key=True, serialize=False
                    ),
                ),
                ("custodia_show_as_absent", models.DateField()),
                ("custodia_start_date", models.DateField()),
                (
                    "family_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.person",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.organization",
                    ),
                ),
            ],
            options={
                "db_table": "person",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.person"
                    ),
                ),
            ],
            options={
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.case"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.person"
                    ),
                ),
            ],
            options={
                "db_table": "charge",
            },
        ),
        migrations.CreateModel(
            name="PersonAtCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.person"
                    ),
                ),
            ],
            options={
                "db_table": "person_at_case",
            },
        ),
        migrations.CreateModel(
            name="PersonAtMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.person"
                    ),
                ),
            ],
            options={
                "db_table": "person_at_meeting",
            },
        ),
        migrations.CreateModel(
            name="PersonChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.person"
                    ),
                ),
            ],
            options={
                "db_table": "person_change",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.organization",
                    ),
                ),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.CreateModel(
            name="RoleRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.role"
                    ),
                ),
            ],
            options={
                "db_table": "role_record",
            },
        ),
        migrations.CreateModel(
            name="RoleRecordMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.person"
                    ),
                ),
                (
                    "role_record",
                    models.ForeignKey(
                        db_column="record_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.rolerecord",
                    ),
                ),
            ],
            options={
                "db_table": "role_record_member",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("num", models.TextField()),
                ("deleted", models.BooleanField(default=False)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sections",
                        to="dst.chapter",
                    ),
                ),
            ],
            options={
                "db_table": "section",
            },
        ),
        migrations.CreateModel(
            name="ManualChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_entered", models.DateTimeField(auto_now_add=True)),
                ("effective_date", models.DateField(blank=True)),
                ("show_date_in_history", models.BooleanField(default=True)),
                ("was_deleted", models.BooleanField(default=False)),
                ("was_created", models.BooleanField(default=False)),
                ("old_content", models.TextField(blank=True, null=True)),
                ("new_content", models.TextField(blank=True, null=True)),
                ("old_title", models.CharField()),
                ("new_title", models.CharField()),
                ("old_num", models.CharField()),
                ("new_num", models.CharField()),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="dst.chapter",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="dst.entry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="dst.section",
                    ),
                ),
            ],
            options={
                "db_table": "manual_change",
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="dst.section",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("use_student_display", models.BooleanField()),
                ("show_in_jc", models.BooleanField()),
                ("show_in_attendance", models.BooleanField()),
                ("show_in_menu", models.BooleanField()),
                ("show_in_account_balances", models.BooleanField()),
                ("show_in_roles", models.BooleanField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.organization",
                    ),
                ),
            ],
            options={
                "db_table": "tag",
            },
        ),
        migrations.CreateModel(
            name="PersonTagChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("was_add", models.BooleanField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.person"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.tag"
                    ),
                ),
            ],
            options={
                "db_table": "person_tag_change",
            },
        ),
        migrations.AddField(
            model_name="person",
            name="tags",
            field=models.ManyToManyField(db_table="person_tag", to="dst.tag"),
        ),
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.organization",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.tag"
                    ),
                ),
            ],
            options={
                "db_table": "notification_rule",
            },
        ),
        migrations.CreateModel(
            name="MailchimpSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.tag"
                    ),
                ),
            ],
            options={
                "db_table": "mailchimp_sync",
            },
        ),
        migrations.CreateModel(
            name="CompletedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.comment"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.person"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.task"
                    ),
                ),
            ],
            options={
                "db_table": "completed_task",
            },
        ),
        migrations.CreateModel(
            name="TaskList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.organization",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.tag"
                    ),
                ),
            ],
            options={
                "db_table": "task_list",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="task_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="dst.tasklist"
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.organization",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": 'public"."user_role',
            },
        ),
        migrations.CreateModel(
            name="CaseReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referenced_case",
                    models.ForeignKey(
                        db_column="referenced_case",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.case",
                    ),
                ),
                (
                    "referencing_case",
                    models.ForeignKey(
                        db_column="referencing_case",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_reference_cases",
                        to="dst.case",
                    ),
                ),
            ],
            options={
                "db_table": "case_reference",
                "constraints": [
                    models.UniqueConstraint(
                        models.F("referenced_case"),
                        models.F("referencing_case"),
                        name="uk_case_case",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChargeReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge",
                    models.ForeignKey(
                        db_column="referenced_charge",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.charge",
                    ),
                ),
                (
                    "the_case",
                    models.ForeignKey(
                        db_column="referencing_case",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dst.case",
                    ),
                ),
            ],
            options={
                "db_table": "charge_reference",
                "constraints": [
                    models.UniqueConstraint(
                        models.F("charge"), models.F("the_case"), name="uk_charge_case"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendanceWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monday", models.DateField()),
                ("extra_hours", models.FloatField(default=0)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.person"
                    ),
                ),
            ],
            options={
                "db_table": "attendance_week",
                "indexes": [
                    models.Index(models.F("monday"), name="attendance_week_monday_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("person"), models.F("monday"), name="u_attendance_week"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendanceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("code", models.CharField(blank=True, max_length=64, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("off_campus_departure_time", models.TimeField(blank=True, null=True)),
                ("off_campus_return_time", models.TimeField(blank=True, null=True)),
                (
                    "off_campus_minutes_exempted",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dst.person"
                    ),
                ),
            ],
            options={
                "db_table": "attendance_day",
                "indexes": [
                    models.Index(models.F("day"), name="attendance_day_day_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("person"), models.F("day"), name="u_attendance_day"
                    )
                ],
            },
        ),
    ]
