# Generated by Django 5.1.6 on 2025-12-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dst", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        default="person",
                        max_length=64,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("integer", "Integer"),
                            ("number", "Number"),
                            ("controlledNumber", "Controlled Number"),
                            ("currency", "Currency"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                            ("toggle", "Toggle"),
                            ("radioGroup", "Radio Group"),
                            ("checkboxGroup", "Checkbox Group"),
                            ("select", "Select"),
                            ("peopleSelect", "People Select"),
                        ],
                        default="text",
                        max_length=64,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("help_text", models.TextField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("required", models.BooleanField(default=False)),
                ("disabled", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                ("type_props", models.JSONField(blank=True, default=dict)),
                ("type_validation", models.JSONField(blank=True, default=dict)),
                ("default_value", models.JSONField(blank=True, null=True)),
                ("required_if", models.JSONField(blank=True, default=list)),
                ("disabled_if", models.JSONField(blank=True, default=list)),
                ("visible_to_role_ids", models.JSONField(blank=True, default=list)),
                ("editable_by_role_ids", models.JSONField(blank=True, default=list)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custom_fields",
                        to="dst.organization",
                    ),
                ),
            ],
            options={
                "db_table": "custom_fields",
                "indexes": [
                    models.Index(
                        fields=["organization", "entity_type"],
                        name="custom_fields_org_entity_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=["organization", "entity_type", "label"],
                        name="custom_field_unique_label_per_entity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_id", models.BigIntegerField()),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_integer", models.BigIntegerField(blank=True, null=True)),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=30, null=True
                    ),
                ),
                (
                    "value_currency",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                ("value_datetime", models.DateTimeField(blank=True, null=True)),
                ("value_option_ids", models.JSONField(blank=True, null=True)),
                ("value_person_ids", models.JSONField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "custom_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="dst.customfield",
                    ),
                ),
            ],
            options={
                "db_table": "custom_field_values",
                "indexes": [
                    models.Index(
                        fields=["custom_field"],
                        name="custom_field_values_field_idx",
                    ),
                    models.Index(
                        fields=["entity_id"], name="custom_field_values_entity_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=["custom_field", "entity_id"],
                        name="custom_field_value_unique_per_entity",
                    )
                ],
            },
        ),
    ]
