#!/bin/bash

set -ex

# Make sure that there are no uncommitted changes
git diff-index --quiet HEAD --

### Play Framework & frontend assets
npm install
npm run compile
./sbt.sh clean dist
rsync -v -h --progress target/universal/demschooltools-1.1.zip evan@demschooltools.com:/home/evan/


# -r is necessary here because ls-tree includes some symbolic link directories
# and we want to include the files that are contained in them.
git ls-tree -r --name-only head django | xargs zip -r django

# These files are generated by the Webpack build and not in git
zip django django/static/js/custodia.js*

scp django.zip evan@demschooltools.com:/home/evan/

rm django.zip
