#!/bin/bash

set -ex

# Make sure that there are no uncommitted changes
git diff-index --quiet HEAD --

### Play Framework stuff
npm install
./sbt.sh clean dist
rsync -v -h --progress target/universal/demschooltools-1.1.zip evan@demschooltools.com:/home/evan/


## Custodia & Django stuff
rm -rf custodia/dist
(cd custodia && npm install && npm run compile)

# -r is necessary here because ls-tree includes some symbolic link directories
# and we want to include the files that are contained in them.
git ls-tree -r --name-only head django | xargs zip -r django

# These files are generated by Custodia's build process and not in git
zip django django/static/js/custodia.js*

scp django.zip evan@demschooltools.com:/home/evan/

rm django.zip

cat << EOF
Build and copy successful. Now ssh to the DST machine and run
    ./run_play.sh
    ./run_django.sh
EOF
