#!/bin/bash

set -ex

# Make sure that there are no uncommitted changes
git diff-index --quiet HEAD --

### Play Framework stuff
npm install
./sbt.sh clean dist
rsync -v -h --progress target/universal/demschooltools-1.1.zip evan@demschooltools.com:/home/evan/


## React & Django stuff
(cd react && npm install && npm run build)

# -r is necessary here because ls-tree includes some symbolic link directories
# and we want to include the files that are contained in them.
git ls-tree -r --name-only head django | xargs zip -r django

# These files are generated by vite's build process and not in git
zip -r django django/static-vite/

rsync -v -h --progress django.zip evan@demschooltools.com:/home/evan/

rm django.zip

cat << EOF
Build and copy successful. Now ssh to the DST machine and run
    ./run_play.sh
    ./run_django.sh
EOF
