#!/bin/bash

export APPLICATION_SECRET="1234567890"
export GOOGLE_CLIENT_SECRET="GOOG"
export FACEBOOK_CLIENT_SECRET="FACE"
export SES_PASSWORD="SES"
export CUSTODIA_PASSWORD="web"
export ROLLBAR_TOKEN="${ROLLBAR_TOKEN:empty-rollbar-token}"
