var exports = {
    studentEvents:{
        LOADED: 'STUDENTEVENTS.LOADED',
        STUDENT_LOADED: 'STUDENTEVENTS.STUDENTLOADED',
        MARKED_ABSENT: 'STUDENTEVENTS.MARKED_ABSENT',
        STUDENT_SWIPED: 'STUDENTEVENTS.STUDENT_SWIPED',
        EXCUSED: 'STUDENTEVENTS.EXCUSED'
    },
    systemEvents: {
        FLASH: 'SYSTEMEVENTS.FLASH'
    }
};

module.exports = exports;