var exports = {
    studentEvents:{
        LOADED: 'STUDENTEVENTS.LOADED',
        STUDENT_LOADED: 'STUDENTEVENTS.STUDENTLOADED',
        MARKED_ABSENT: 'STUDENTEVENTS.MARKED_ABSENT',
        STUDENT_SWIPED: 'STUDENTEVENTS.STUDENT_SWIPED',
        EXCUSED: 'STUDENTEVENTS.EXCUSED'
    },
    systemEvents: {
        TODAY_LOADED: 'SYSTEMEVENTS.TODAYLOADED',
        FLASH: 'SYSTEMEVENTS.FLASH'
    },
    reportEvents: {
        YEARS_LOADED: 'REPORTEVENTS.YEARSLOADED',
        REPORT_LOADED: 'REPORTEVENT.REPORTLOADED',
        PERIOD_CREATED: 'REPORTEVENT.PERIOD_CREATED'
    }
};

module.exports = exports;