DROP FUNCTION IF EXISTS school_days(text);
--;;
DROP VIEW IF EXISTS roundedswipes;
--;;
DROP TABLE IF EXISTS swipes;
--;;
DROP TABLE IF EXISTS overseer.session_store;
--;;
DROP TABLE IF EXISTS students;
--;;
DROP TABLE IF EXISTS excuses;
--;;
DROP TABLE IF EXISTS overrides;
--;;
DROP TABLE IF EXISTS years;
