create schema phillyfreeschool;
--;;
alter TABLE years set schema phillyfreeschool;
--;;
alter TABLE students set schema phillyfreeschool;
--;;
alter TABLE classes set schema phillyfreeschool;
--;;
alter TABLE classes_X_students set schema phillyfreeschool;
--;;
alter VIEW roundedswipes set schema phillyfreeschool;
--;;
alter TABLE swipes set schema phillyfreeschool;
--;;
alter TABLE excuses set schema phillyfreeschool;
--;;
alter TABLE overrides set schema phillyfreeschool;
--;;
alter FUNCTION school_days(text, bigint) set schema phillyfreeschool;
