DROP TABLE IF EXISTS demo.years;
--;;
DROP TABLE IF EXISTS demo.classes_X_students;
--;;
DROP TABLE IF EXISTS demo.classes;
--;;
DROP FUNCTION IF EXISTS demo.school_days(text);
--;;
DROP FUNCTION IF EXISTS demo.school_days(text, bigint);
--;;
DROP VIEW IF EXISTS demo.roundedswipes;
--;;
DROP TABLE IF EXISTS demo.swipes;
--;;
DROP TABLE IF EXISTS demo.students;
--;;
DROP TABLE IF EXISTS demo.excuses;
--;;
DROP TABLE IF EXISTS demo.overrides;
