# Generated by Django 5.1.5 on 2025-02-11 02:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunSQL(
            """
--- This has to be run before the django.contrib.admin migrations. If
--- not, then the django_admin_log table will reference overseer.users
--- instead of public.users.
ALTER TABLE overseer.users rename to old_users;

ALTER TABLE overseer.classes rename to old_classes;
ALTER TABLE overseer.classes_x_students rename to old_classes_x_students;
ALTER TABLE overseer.session_store rename to old_session_store;
            """,
        ),
        migrations.RunSQL("""
ALTER TABLE public.person ADD COLUMN custodia_show_as_absent date NULL;
ALTER TABLE public.person ADD COLUMN custodia_start_date date NULL;

UPDATE public.person p set custodia_show_as_absent=s.show_as_absent
   FROM overseer.students s where s.dst_id=p.person_id;
UPDATE public.person p set custodia_start_date=s.start_date
   FROM overseer.students s where s.dst_id=p.person_id;
"""),
        migrations.RunSQL(
            """
alter table overseer.excuses add column person_id  int4 null;
ALTER TABLE overseer.excuses ADD CONSTRAINT fk_excuses_person FOREIGN KEY (person_id) REFERENCES public.person(person_id);
alter table overseer.swipes add column person_id  int4 null;
ALTER TABLE overseer.swipes ADD CONSTRAINT fk_person FOREIGN KEY (person_id) REFERENCES public.person(person_id);
alter table overseer.students_required_minutes add column person_id  int4 null;
ALTER TABLE overseer.students_required_minutes ADD CONSTRAINT fk_person FOREIGN KEY (person_id) REFERENCES public.person(person_id);
alter table overseer.overrides add column person_id  int4 null;
ALTER TABLE overseer.overrides ADD CONSTRAINT fk_person FOREIGN KEY (person_id) REFERENCES public.person(person_id);

UPDATE overseer.excuses e set person_id=s.dst_id
   FROM overseer.students s, public.person p where s._id=e.student_id and s.dst_id=p.person_id;
delete FROM overseer.excuses where person_id is null;
UPDATE overseer.swipes e set person_id=s.dst_id
   FROM overseer.students s, public.person p where s._id=e.student_id and s.dst_id=p.person_id;
delete FROM overseer.swipes where person_id is null;
UPDATE overseer.students_required_minutes e set person_id=s.dst_id
   FROM overseer.students s, public.person p where s._id=e.student_id and s.dst_id=p.person_id;
delete FROM overseer.students_required_minutes where person_id is null;
UPDATE overseer.overrides e set person_id=s.dst_id
   FROM overseer.students s, public.person p where s._id=e.student_id and s.dst_id=p.person_id;
delete FROM overseer.overrides where person_id is null;

ALTER TABLE overseer.students rename to old_students;

alter table overseer.excuses alter column person_id set not null;
alter table overseer.swipes alter column person_id set not null;
alter table overseer.students_required_minutes alter column person_id set not null;
alter table overseer.overrides alter column person_id set not null;

alter table overseer.excuses add constraint uniq_excuses_person_date unique(person_id, inserted_date);
alter table overseer.overrides add constraint uniq_overrides_person_date unique(person_id, inserted_date);

alter table overseer.swipes drop column rounded_in_time;
alter table overseer.swipes drop column rounded_out_time;
alter table overseer.swipes drop column intervalmin;
create index on overseer.swipes (person_id, swipe_day);
create index on overseer.swipes (swipe_day, person_id);
alter table overseer.swipes alter column swipe_day set not null;

alter table overseer.excuses drop column student_id;
alter table overseer.swipes drop column student_id cascade;
alter table overseer.students_required_minutes drop column student_id cascade;
alter table overseer.overrides drop column student_id;
                                """
        ),
        # Combine overseer.schools with public.organization, and fix a bunch of things
        # about the years table.
        migrations.RunSQL(
            """
ALTER TABLE organization ADD COLUMN	timezone varchar(255) DEFAULT 'America/New_York' NOT NULL;
UPDATE organization o set timezone=s.timezone FROM overseer.schools s where s._id=o.id;

ALTER TABLE overseer.years ALTER COLUMN school_id rename to organization_id;
ALTER TABLE overseer.years DROP CONSTRAINT fk_class_school;
ALTER TABLE overseer.years ADD CONSTRAINT fk_org FOREIGN KEY (organization_id) REFERENCES organization(id);
ALTER TABLE overseer.years ALTER COLUMN organization_id DROP DEFAULT;
ALTER TABLE overseer.years ALTER COLUMN name SET NOT NULL;
ALTER TABLE overseer.years ALTER COLUMN inserted_date SET NOT NULL;
ALTER TABLE overseer.years ALTER COLUMN inserted_date DROP DEFAULT;
ALTER TABLE overseer.years ALTER COLUMN inserted_date type timestamp with time zone;

delete from overseer.years where from_date is null or to_date is null;
ALTER TABLE overseer.years ALTER COLUMN from_date SET NOT NULL;
ALTER TABLE overseer.years ALTER COLUMN to_date SET NOT NULL;

-- Delete duplicate organization_id, name
DELETE FROM overseer.years a USING (
    SELECT MIN(ctid) as ctid, organization_id, name
    FROM overseer.years
    GROUP BY organization_id, name HAVING COUNT(*) > 1
) b
WHERE a.organization_id = b.organization_id and a.name=b.name
AND a.ctid <> b.ctid;
ALTER TABLE overseer.years ADD CONSTRAINT unique_name UNIQUE (organization_id, name);

ALTER TABLE overseer.schools rename to old_schools;

ALTER TABLE organization ADD COLUMN late_time TIME DEFAULT '10:15:00'::time without time zone NULL;
ALTER TABLE organization ALTER COLUMN late_time DROP DEFAULT;
"""
        ),
        # Disallow null in times for swipes
        migrations.RunSQL(
            """
DELETE FROM overseer.swipes WHERE in_time is NULL;
ALTER TABLE overseer.swipes ALTER COLUMN in_time SET NOT NULL;
            """
        ),
        # Add fields needed for django auth/user
        migrations.RunSQL("""
ALTER TABLE public.users ADD COLUMN date_joined timestamptz NOT NULL default '2000-01-01';
ALTER TABLE public.users ADD COLUMN last_login timestamptz NULL default NULL;
ALTER TABLE public.users ADD COLUMN first_name varchar(150) NOT NULL default '';
ALTER TABLE public.users ADD COLUMN last_name varchar(150) NOT NULL default '';
ALTER TABLE public.users ADD COLUMN is_superuser bool NOT NULL default false;
ALTER TABLE public.users ADD COLUMN is_staff bool NOT NULL default false;
ALTER TABLE public.users ADD COLUMN is_active bool NOT NULL default true;
ALTER TABLE public.users ADD COLUMN username varchar(150) NOT NULL default '';
"""),
        # Set late_time at the school level instead of class level
        # TODO: Do this on public.organization instead of school
        migrations.RunSQL("""
"""),
        # Add unique ID to students_required_minutes table
        migrations.RunSQL("""
ALTER TABLE overseer.students_required_minutes ADD COLUMN id SERIAL PRIMARY KEY;
"""),
    ]
