# Generated by Django 5.1.5 on 2025-02-11 02:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        # This has to be run before the django.contrib.admin migrations. If
        # not, then the django_admin_log table will reference overseer.users
        # instead of public.users.
        migrations.RunSQL(
            "ALTER TABLE overseer.users rename to old_users",
            "ALTER TABLE overseer.old_users rename to users",
        )
    ]
